pcm.usbmic_resampled {
    type plug
    slave {
	pcm "plughw:1,0"
	channels 1
	rate 24000
	format S16_LE
    }
    hint {
	description "Resample audio to 24k"
    }
}

pcm.usbmiclav {
    type dsnoop
    ipc_key 466752
    ipc_perm 0666
    slave {
        pcm "hw:CARD=Device,DEV=0"
        channels 1
        rate 48000
    }
    hint {
        description "LOOPBACK_DEV_44"
    }
}

pcm.usbmicmxl {
    type dsnoop
    ipc_key 485616
    ipc_perm 0666
    slave {
        pcm "hw:CARD=CODEC,DEV=0"
        channels 1
        rate 48000
    }
    hint {
        description "LOOPBACK_DEV_404"
    }
}

pcm.usbmicwebcam {
    type dsnoop
    ipc_key 485616
    ipc_perm 0666
    slave {
        pcm "hw:CARD=C930e,DEV=0"
        channels 1
        rate 48000
    }
    hint {
        description "LOOPBACK_DEV_404_2"
    }
}
