#!/bin/bash

DEFAULT_DOCKER_IMAGE="docker-registry.jibo.media.mit.edu:5000/mitprg/ros-bundle:triadic-interaction"
DEFAULT_COMMAND="python3 dyadic-controller.py"

DOCKER_IMAGE="$DEFAULT_DOCKER_IMAGE"
COMMAND="$DEFAULT_COMMAND"

if [[ $1 == "bash" ]]; then
    COMMAND="bash"
    shift
fi

if [[ $1 == "install" ]]; then
    COMMAND="install"
    shift
fi

if [[ $# > 0 ]]; then
    DOCKER_IMAGE="$1"
    shift
fi

if [[ $1 == "bash" ]]; then
    COMMAND="bash"
    shift
fi

if [[ $1 == "install" ]]; then
    COMMAND="install"
    shift
fi

xhost +
pactl load-module module-native-protocol-unix socket=/tmp/pulseaudio.socket 2>/dev/null

RESTART_ARG=""
TERMINAL_ARG="-it"

if [[ $COMMAND == "install" ]]; then
    COMMAND="$DEFAULT_COMMAND"
    RESTART_ARG="--restart unless-stopped"
    TERMINAL_ARG="-d"
    echo "installing $DOCKER_IMAGE with --restart unless-stopped"
else
    echo "running $COMMAND $@ with $DOCKER_IMAGE"
fi

docker run \
       $TERMINAL_ARG \
       --restart always \
       --privileged \
       --entrypoint /ros_auto_dyadic_entrypoint.sh \
       --env PRGUID=$UID \
       -v /etc/timezone:/etc/timezone:ro \
       -v /etc/localtime:/etc/localtime:ro \
       -v /home/prg/rosbags:/home/prg/rosbags -v /home/prg/catkin_ws/src/output_data:/home/prg/catkin_ws/src/output_data \
       -v /etc/machine-id:/etc/machine-id \
       -v /dev:/dev \
       -v /var/lib/dbus:/var/lib/dbus \
       --env PULSE_SERVER=unix:/tmp/pulseaudio.socket \
       --env PULSE_COOKIE=/tmp/pulseaudio.cookie \
       --volume /tmp:/tmp \
       --network host \
       --env DISPLAY=:0 \
       $DOCKER_IMAGE $COMMAND $@
